marchine/urls.py
from django.urls import path

from . import views

app_name = 'marchine'
urlpatterns = [
    path('', views.home, name='home'),
    path('createmachine/', views.createmarchine, name='createmarchine'),
    path('editmachine/', views.editmarchine, name='editmarchine'),
    path('deletemarchine/', views.deletemarchine, name='deletemarchine'),
]

settings/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('marchine.urls')),
]

marchine/models.py
from django.db import models
from django.utils import timezone


# Create your models here.
class Marchine(models.Model):
    valor = models.IntegerField(default=0)
    acao = models.BooleanField(default=False)
    data_criacao = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f'{self.valor}'

    class Meta:
        verbose_name = 'Marchine'
        verbose_name_plural = 'Marchines'
        ordering = ['-data_criacao']

marchine/views.py
from datetime import timedelta

from django.contrib import messages
from django.db.models import Sum
from django.http.response import Http404
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.utils import timezone
from parse import parse

from .models import Marchine


# Create your views here.
def home(request):
    template = 'marchine/pages/home.html'
    dadosmarchines = Marchine.objects.all().order_by('-data_criacao')
\
    # calcula o total diario
    ValordiarioEntrada = Marchine.objects.all().filter(
        acao=True, data_criacao__day=timezone.now().day).aggregate(Sum('valor'))  # noqa
    if ValordiarioEntrada['valor__sum'] is None:
        ValordiarioEntrada['valor__sum'] = 0

    ValordiarioSaida = Marchine.objects.all().filter(
        acao=False, data_criacao__day=timezone.now().day).aggregate(Sum('valor'))  # noqa
    if ValordiarioSaida['valor__sum'] is None:
        ValordiarioSaida['valor__sum'] = 0

    TotalDiario = ValordiarioEntrada['valor__sum'] -\
        ValordiarioSaida['valor__sum']

    # calcula o total mensal
    ValorMensalEntrada = Marchine.objects.all().filter(
        acao=True, data_criacao__month=timezone.now().month).aggregate(Sum('valor'))  # noqa
    if ValorMensalEntrada['valor__sum'] is None:
        ValorMensalEntrada['valor__sum'] = 0
    ValorMensalSaida = Marchine.objects.all().filter(
        acao=False, data_criacao__month=timezone.now().month).aggregate(Sum('valor'))  # noqa
    if ValorMensalSaida['valor__sum'] is None:
        ValorMensalSaida['valor__sum'] = 0

    TotalMensal = ValorMensalEntrada['valor__sum'] - \
        ValorMensalSaida['valor__sum']

    # calcula o total anual
    ValorAnualEntrada = Marchine.objects.all().filter(
        acao=True, data_criacao__year=timezone.now().year).aggregate(Sum('valor'))  # noqa
    if ValorAnualEntrada['valor__sum'] is None:
        ValorAnualEntrada['valor__sum'] = 0

    ValorAnualSaida = Marchine.objects.all().filter(
        acao=False, data_criacao__year=timezone.now().year).aggregate(Sum('valor'))  # noqa
    if ValorAnualSaida['valor__sum'] is None:
        ValorAnualSaida['valor__sum'] = 0

    TotalAnual = ValorAnualEntrada['valor__sum'] - \
        ValorAnualSaida['valor__sum']

    contexto = {
        'dadosmarchines': dadosmarchines,
        'TotalDiario': TotalDiario,
        'TotalMensal': TotalMensal,
        'TotalAnual': TotalAnual,

    }

    return render(request, template, contexto)


def createmarchine(request):
    if not request.POST:
        raise Http404()
    if request.method == 'POST':
        valor = request.POST.get('valor')
        if 'acao' in request.POST:
            acao = request.POST.get('acao')
            acao = True
        else:
            acao = False
        Marchine.objects.create(valor=valor, acao=acao)
        messages.success(request, 'Data saved successfully!')
        return redirect('marchine:home')
    else:
        messages.error(request, 'Data not saved!')
        return redirect(reverse('marchine:home'))


def editmarchine(request):
    if not request.POST:
        raise Http404()
    id = request.POST.get('marchine_id')
    marchineedit = get_object_or_404(Marchine, id=id)
    if request.method == 'POST':
        marchineedit.valor = request.POST.get('valor')
        if 'acao' in request.POST:
            marchineedit.acao = request.POST.get('acao')
            marchineedit.acao = True
        else:
            marchineedit.acao = False
        marchineedit.save()
        messages.success(request, 'Data saved successfully!')
        return redirect('marchine:home')
    else:
        messages.error(request, 'Data not saved!')
        return redirect(reverse('marchine:home'))


def deletemarchine(request):
    if not request.POST:
        raise Http404()

    id = request.POST.get('marchine_id')

    marchinedelete = get_object_or_404(Marchine, id=id)

    marchinedelete.delete()
    messages.success(request, 'Data successfully deleted!')
    return redirect(reverse('marchine:home'))

marchine/templates/marchine/modal/_createmarchine.html
<div>
  <br>
  <br>
<div class="d-grid gap-2 col-6 mx-auto">

  <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#createModal">Criar Financas</button>
  <!-- Modal -->
<div class="modal fade" id="createModal" tabindex="-1" aria-labelledby="createModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="createModalLabel">Salvar Dados</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <form action={% url 'marchine:createmarchine' %} method="POST">
          {% csrf_token %}
          <div class="form-floating mb-3">
            <input type="text" class="form-control" id="floatingInput" name="valor" placeholder="valor" />
            <label for="floatingInput">Valor</label>
          </div>

          <div class="custom-control custom-checkbox">
            <input type="checkbox" class="custom-control-input" name="acao" id="acao" checked>
            <label class="custom-control-label" for="acao">Entrada</label>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancela</button>
          <button type="submit" class="btn btn-primary">Salvar</button>
        </div>
      </form>
    </div>
  </div>
</div>
</div>
</div>

marchine/templates/marchine/modal/_deletemarchine.html
<button type="button" class="btn btn-outline-danger" data-bs-toggle="modal" data-bs-target="#deleteModal{{ dadosmarchine.id }}">Delete</button>

<!-- Modal -->
<div class="modal fade" id="deleteModal{{ dadosmarchine.id }}" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="deleteModalLabel">Deletar {{ dadosmarchine.name }}</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <form action={% url 'marchine:deletemarchine' %} method="POST">
        {% csrf_token %}
        <input type="hidden" name="marchine_id" value="{{dadosmarchine.id}}" />
        <div class="modal-body">
          <h2>Tem certeza que deseja apagar? {{ dadosmarchine.valor }}?</h2>
          <h2>Essa ação não poderá ser revertida.</h2>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
          <button type="submit" class="btn btn-danger">Deletar</button>
        </div>
      </form>
    </div>
  </div>
</div>

marchine/templates/marchine/modal/_editmarchine.html
<button type="button" class="btn btn-outline-warning" data-bs-toggle="modal" data-bs-target="#editModal{{ dadosmarchine.id }}">Edit</button>

<!-- Modal -->
<div class="modal fade" id="editModal{{ dadosmarchine.id }}" tabindex="-1" aria-labelledby="editModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="editModalLabel">Editar {{ dadosmarchine.valor }} reais</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <form action={% url 'marchine:editmarchine' %} method="POST">
        {% csrf_token %}
        <div class="modal-body">
          <input type="hidden" name="marchine_id" value="{{dadosmarchine.id}}" />
          <div class="form-floating mb-3">
            <input type="text" class="form-control" name="valor" id="floatingInput" placeholder="valor" value="{{ dadosmarchine.valor }}" />
            <label for="floatingInput">Valor</label>
          </div>
          <div class="custom-control custom-checkbox">
            {% if dadosmarchine.acao == True %}
              <input type="checkbox" class="custom-control-input" name="acao" id="acao" value="{{ dadosmarchine.acao }}" checked>
            {%else%}
              <input type="checkbox" class="custom-control-input" name="acao" id="acao" >
            {% endif %}
            
            <label class="custom-control-label" for="acao" >Entrada</label>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
          <button type="submit" class="btn btn-warning">Salvar</button>
        </div>
      </form>
    </div>
  </div>
</div>

marchine/templates/marchine/pages/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Finanças pessoais</title>
    <link rel="shortcut icon" href="https://raw.githubusercontent.com/arroz01/machine_learnig/main/frontend/img/favicon.png">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        .corpo {
            margin: 1.3rem 4rem 1rem 4rem;
           
        }
        
        h2, p, .modal-header,label{
            color: black;
        }
        
        .card {
            margin: 0 auto; 
            float: none;
            margin-bottom: 10px;
        }
    </style>
</head>
<header>
    {% include 'marchine/partial/_nav.html' %}
</header>
<body>
    <div class="corpo">
        {% include 'marchine/partial/_card.html' %}
        {% include 'marchine/modal/_createmarchine.html' %}
        <br>
        {% include 'marchine/partial/_table.html' %}
        {% include 'marchine/partial/message.html' %}
    </div>
</body>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js"></script>
</html>

marchine/templates/marchine/partial/_card.html
<div class="center row row-cols-xl-3 row-cols-sm-2 row-cols-md-3 row-cols-lg-3 text-center">
    <div class="card border-light mb-3 text-bg-light" style="max-width: 18rem;">
        <div class="card-header">Média Diária</div>
        <div class="card-body">
            <h5 class="card-title">R$ {{TotalMensal}}</h5>
        </div>
    </div>
    <div class="col">
        <div class="card border-light text-bg-success mb-3" style="max-width: 18rem;">
            <div class="card-header">Média Mensal</div>
            <div class="card-body">
                <h5 class="card-title">R$ {{TotalMensal}}</h5>
            </div>
        </div>
    </div>
    <div class="col">
        <div class="card border-light text-bg-warning mb-3" style="max-width: 18rem;">
            <div class="card-header">Média Anual</div>
            <div class="card-body">
                <h5 class="card-title">R$ {{TotalMensal}}</h5>
            </div>
        </div>
    </div>
</div>

marchine/templates/marchine/partial/_nav.html
<header>
    <nav class="navbar bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">
                <img src="https://raw.githubusercontent.com/arroz01/machine_learnig/33a447873b21da26cea6c9770ad7a4fca61a2180/frontend/img/laze.png" alt="Bootstrap" width="60" height="60">
            </a>
            <span class="navbar-brand mb-0 h1">Blaze Finance</span>
        </div>
    </nav>
</header>

marchine/templates/marchine/partial/_table.html
<div>
    <table class="table table-dark table-striped">
        <thead>
            <tr>
                <th scope="col">Codigo</th>
                <th scope="col">Valor</th>
                <th scope="col">Entrada/Saída</th>
                <th scope="col">Data</th>
                <th scope="col">Ações</th>
            </tr>
        </thead>
        <tbody>
            {% for dadosmarchine in dadosmarchines %}
            <tr>
                <td scope="row">{{ dadosmarchine.id }}</td>
                <td>R$ {{ dadosmarchine.valor }}</td>
                    {% if dadosmarchine.acao == True %}
                        <td>Entrada</td>
                    {%else%}
                        <td>Saída</td>
                    {% endif %}
                <td>{{ dadosmarchine.data_criacao|date:"d/m/y" }}</td>
                <td>
                    {% include 'marchine/modal/_editmarchine.html' %}
                    {% include 'marchine/modal/_deletemarchine.html' %}
                </td>
                {% endfor %}
            </tr>
        </tbody>
    </table>

marchine/templates/marchine/partial/message.html
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
{% if messages %}
    {% for message in messages %}
        <script>
            swal({
                text: "{{ message }}",
                icon: "{{ message.tags }}",
              });
        </script>
    {% endfor %}
{% endif %}